I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mage.rpy", line 15, in script
    jump mage_idle
ScriptError: could not find label 'mage_idle'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/mage.rpy", line 15, in script
    jump mage_idle
  File "/Users/kiramki/Downloads/renpy/renpy/ast.py", line 1705, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/kiramki/Downloads/renpy/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'mage_idle'.

macOS-15.2-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Forever Yours, The Devil 1.0
Thu Jan 16 00:52:15 2025
