I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 388, in script
    menu opening_priest_questions:
  File "game/script.rpy", line 394, in <module>
    "{b}You have forgotten something terribly important{/b}" if forgotten_memory == False:
NameError: name 'forgotten_memory' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 388, in script
    menu opening_priest_questions:
  File "/Users/kiramki/Downloads/renpy/renpy/ast.py", line 1625, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "/Users/kiramki/Downloads/renpy/renpy/exports/menuexports.py", line 100, in menu
    condition = renpy.python.py_eval(condition)
  File "/Users/kiramki/Downloads/renpy/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/kiramki/Downloads/renpy/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 394, in <module>
    "{b}You have forgotten something terribly important{/b}" if forgotten_memory == False:
NameError: name 'forgotten_memory' is not defined

macOS-15.2-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Forever Yours, The Devil 1.0
Wed Jan 29 16:13:49 2025
